### PR TITLE
configurable level file type

### LINKED ISSUE #23: Rojo build format config
Rbx-dom currently has pretty weak support for Roblox's binary format (rbxl and rbxm). It would be super sweet if there was a way to configure vscode-rojo to use the xml format ( rbxlx and rbxmx ) when building.

### PR DESCRIPTION
**Pull request by lukechatton**
This PR adds a "level file type" configuration option. The selection has two fields: rbxl and rbxlx.

This should resolve #23.

Note: I was only able to test this locally by setting `preLaunchTask` to `npm: compile` in `launch.json`. I've switched it back to `npm: watch` in the PR.

### CODE REVIEW

**Comment by evaera** [comment]
This PR is most of the way there, but we should allow the file type to be customizable for model files as well as place files.

The setting should be renamed to `buildFileFormat`, and the options should be "XML" and "binary", with the default being "XML".

Then, the file extension should be determined based on if the config root is the data model or not:

For XML: `rbxlx` or `rbxmx` 
For binary: `rbxl` or `rbxm`

**Comment by evaera** [comment]
Hi, do you plan to make these changes or should I plan to work on them myself?

**Comment by lukechatton** [comment]
I can work on this tonight. I'l try to get a PR submitted then.

**Comment by lukechatton** [comment]
Alright, 

> This PR is most of the way there, but we should allow the file type to be customizable for model files as well as place files.
> 
> The setting should be renamed to `buildFileFormat`, and the options should be "XML" and "binary", with the default being "XML".
> 
> Then, the file extension should be determined based on if the config root is the data model or not:
> 
> For XML: `rbxlx` or `rbxmx`
> For binary: `rbxl` or `rbxm`

Done!

**Comment by lukechatton** [comment]
So this change actually broke my project's setup... 

Following @LPGhatguy's [example project](https://github.com/LPGhatguy/roads), the tree classname is set to "DataModel" in `default.project.json`. 

Using this setup, the vscode extension will output as a rbxmx file instead of rbxlx. Not sure if I'm misunderstanding something... Thought I'd report it anyways. I'm forcing the output to be rbxlx in a local version for the time being.

**Pull request merged**
